pub struct IsleApp {
	hd_path: Option<String>,
	cd_path: Option<String>,
	device_id: Option<String>,
	save_path: Option<String>,
	full_screen: bool,
	flip_surfaces: bool,
	back_buffers_in_vram: bool,
	using_8_bit: bool,
	using_16_bit: bool,
	unknown_0x24: i32,
	use_3d_sound: bool,
	use_music: bool,
	use_joystick: bool,
	joystick_index: i32,
	wide_view_angle: bool,
	island_quality: i32,
	island_texture: i32,
	game_started: bool,
	frame_delta: i64,
}